=== Gumtree/gumtree/bragg/kowari/au.gov.ansto.bragg.kowari.dra/xml/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by N. Xiong (Australian Nuclear Science and Technology Organisation (ANSTO)) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.ansto.gov.au/bragg/dra/recipeSchema" targetNamespace="http://www.ansto.gov.au/bragg/dra/recipeSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.1">
	<xs:element name="framework">
		<xs:annotation>
			<xs:documentation>framework of the processor chain</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="processor" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ins" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="in" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="dimension" type="xs:integer" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="outs" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="out" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="dimension" type="xs:integer" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="vars" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="var" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="dimension" type="xs:integer" use="optional"/>
												<xs:attribute name="max"/>
												<xs:attribute name="min"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ns1:name" type="xs:string" use="required"/>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="sink" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ins" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="in" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="dimension" type="xs:integer" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="outs" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="out" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="dimension" type="xs:integer" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="vars" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="var" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="dimension" type="xs:integer" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ins">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="in">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="type" type="xs:string" use="required"/>
									<xs:attribute name="dimension" type="xs:integer" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="outs" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="out" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="type" type="xs:string" use="required"/>
									<xs:attribute name="dimension" type="xs:integer" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="vars" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="var" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="type" type="xs:string" use="required"/>
									<xs:attribute name="usage" use="required"/>
									<xs:attribute name="label"/>
									<xs:attribute name="dimension" type="xs:integer" use="optional"/>
									<xs:attribute name="default_value"/>
									<xs:attribute name="max"/>
									<xs:attribute name="min"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="connectors">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="connector">
								<xs:complexType>
									<xs:attribute name="producer" use="required"/>
									<xs:attribute name="consumer" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="agents" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="agent" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="principal" type="xs:string" use="required"/>
									<xs:attribute name="pname" type="xs:string" use="required"/>
									<xs:attribute name="label" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="domain" type="xs:string" default="au.gov.ansto.bragg.dra"/>
			<xs:attribute name="version" type="xs:string"/>
			<xs:attribute name="help_url" type="xs:string"/>
			<xs:attribute name="icon" type="xs:string"/>
			<xs:attribute name="short_description" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Gumtree/gumtree/bragg/echidna/au.gov.ansto.bragg.echidna.dra/xml/Stitching.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by Norman Xiong (Australian Nuclear Science and Technology Organisation (ANSTO)) -->
<!--
    Document   : Stitching.xml
    Created on : 6 December 2006, 10:10
    Author     : nxi
    Description:
        Purpose of the document follows.
-->
<framework xmlns="http://www.ansto.gov.au/bragg/dra/recipeSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.ansto.gov.au/bragg/dra/recipeSchema http://gumtree.ansto.gov.au:9080/nbicms/dat-projects/data-reduction-capability-projects/cicada-the-dav-application-interface-project/xml-schema/recipe.xsd"
 id="010602" name="Stitching Data" domain="au.gov.ansto.bragg.dra" version="2.0" help_url="./help.txt" short_description="Stitching Data" icon="xml/icons/stitching.gif">
	<processor name="Source" class="au.gov.ansto.bragg.echidna.dra.core.Source">
		<ins>
			<in name="source_groupData" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
		<outs>
			<out name="source_outData" type="org.gumtree.data.gdm.core.Group"/>
		</outs>
		<vars>
			<var name="source_dataName" type="java.lang.String"/>
		</vars>
	</processor>
	<processor name="Stitch" class="au.gov.ansto.bragg.echidna.dra.core.Stitching">
		<ins>
			<in name="stitch_input" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
		<outs>
			<out name="stitch_output" type="org.gumtree.data.gdm.core.Group"/>
		</outs>
		<vars>
			<var name="stitch_skip" type="java.lang.Boolean"/>
			<var name="stitch_stop" type="java.lang.Boolean"/>
			<var name="stitch_reverse" type="java.lang.Boolean"/>
		</vars>
	</processor>
	<processor name="Wrap" class="au.gov.ansto.bragg.echidna.dra.core.Wrap">
		<ins>
			<in name="wrap_databag" type="org.gumtree.data.gdm.core.Group"/>
			<in name="wrap_result" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
		<outs>
			<out name="wrap_output" type="org.gumtree.data.gdm.core.Group"/>
		</outs>
		<vars>
			<var name="wrap_inputName" type="java.lang.String"/>
			<var name="wrap_resultName" type="java.lang.String"/>
		</vars>
	</processor>
	<sink name="SourceSink">
		<ins>
			<in name="sourceSink_in" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
	</sink>
	<sink name="dataReduction_result">
		<ins>
			<in name="dataReductionResult_in" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
	</sink>
	<sink name="stitching_result">
		<ins>
			<in name="stitchingResult_in" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
	</sink>
	<ins>
		<in name="frame_databag" type="org.gumtree.data.gdm.core.Group"/>
	</ins>
	<outs>
		<out name="frame_output" type="org.gumtree.data.gdm.core.Group"/>
	</outs>
	<vars>
		<var name="frame_dataName" type="java.lang.String" default_value="backgroundCorrection_result" usage="parameter" label="name of data"/>
		<var name="frame_stitchSkip" type="java.lang.Boolean" default_value="false" usage="option" label="skip stitching"/>
		<var name="frame_stitchStop" type="java.lang.Boolean" default_value="false" usage="option" label="stop after stitching"/>
		<var name="frame_stitchreverse" type="java.lang.Boolean" default_value="true" usage="parameter" label="Tube two theta values reversed"/>
		<var name="frame_resultName" type="java.lang.String" default_value="stitch_result" usage="parameter" label="name of result"/>
	</vars>
	<connectors>
		<connector producer="frame_databag" consumer="source_groupData"/>
		<connector producer="frame_databag" consumer="wrap_databag"/>
		<connector producer="wrap_output" consumer="frame_output"/>
		<connector producer="frame_dataName" consumer="source_dataName"/>
		<connector producer="frame_dataName" consumer="wrap_inputName"/>
		<connector producer="frame_stitchSkip" consumer="stitch_skip"/>
		<connector producer="frame_stitchStop" consumer="stitch_stop"/>
		<connector producer="frame_stitchreverse" consumer="stitch_reverse"/>
		<connector producer="frame_resultName" consumer="wrap_resultName"/>
		<connector producer="source_outData" consumer="stitch_input"/>
		<connector producer="source_outData" consumer="sourceSink_in"/>
		<connector producer="stitch_output" consumer="stitchingResult_in"/>
		<connector producer="stitch_output" consumer="wrap_result"/>
		<connector producer="wrap_output" consumer="dataReductionResult_in"/>
	</connectors>
	<agents>
		<agent name="source_processor" principal="ProcessorAgent" pname="Source" label="Data Source"/>
		<agent name="stitching_processor" principal="ProcessorAgent" pname="Stitch" label="Data Stitching"/>
		<agent name="stitched_signal_port" principal="PortAgent" pname="stitch_output" label="Output Port of Data Stitching"/>
		<agent name="stitched_signal_framework_port" principal="PortAgent" pname="frame_output" label="Frame Output Port of Data Stitching"/>
	</agents>
</framework>

=== Gumtree/gumtree/bragg/wombat/au.gov.ansto.bragg.wombat.dra/xml/histogram.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : histogram.xml
    Created on : 20 July 2007, 16:10
    Author     : nxi
    Description:
        Recipe file of taking a data out from the databag in the wombat algorithm set.
-->
<framework xmlns="http://www.ansto.gov.au/bragg/dra/recipeSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.ansto.gov.au/bragg/dra/recipeSchema http://gumtree.ansto.gov.au:9080/nbicms/dat-projects/data-reduction-capability-projects/cicada-the-dav-application-interface-project/xml-schema/recipe.xsd"
id="250801" 
name="Histogram Data" 
domain="au.gov.ansto.bragg.wombat.dra" 
version="1.0" 
help_url="./help.txt" 
short_description="Realtime histogram data" 
icon="xml/icons/findData.gif"
hidden="false">

	<processor name="HistogramViewer" class="au.gov.ansto.bragg.nbi.dra.experiment.HistogramViewer">
		<ins>
			<in name="histogramViewer_loopIn" type="java.lang.Boolean"/>
		</ins>
		<outs>
			<out name="histogramViewer_data" type="org.gumtree.data.gdm.core.Group"/>
			<out name="histogramViewer_loopOut" type="java.lang.Boolean"/>
		</outs>
		<vars>
			<var name="histogramViewer_host" type="java.lang.String"/>
			<var name="histogramViewer_port" type="java.lang.Integer"/>
			<var name="histogramViewer_interval" type="java.lang.Double"/>
			<var name="histogramViewer_stop" type="java.lang.Boolean"/>
		</vars>
	</processor>
	<processor name="Source" class="au.gov.ansto.bragg.wombat.dra.core.FindData">
		<ins>
			<in name="source_groupData" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
		<outs>
			<out name="source_scanData" type="org.gumtree.data.gdm.core.Group"/>
		</outs>
		<vars>
			<var name="source_dataName" type="java.lang.String"/>
		</vars>
	</processor>
	<processor name="VerticalIntegration" class="au.gov.ansto.bragg.nbi.dra.core.VerticalIntegration" version="1.0.0">
		<ins>
			<in name="verticalIntegration_input" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
		<outs>
			<out name="verticalIntegration_output" type="org.gumtree.data.gdm.core.Group"/>
		</outs>
		<vars>
			<var name="verticalIntegration_region" type="org.gumtree.data.gdm.core.Group"/>
			<var name="vertInt_scale" type="java.lang.Boolean"/>
		</vars>
	</processor>
	<sink name="SourceSink">
		<ins>
			<in name="sourceSink_in" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
	</sink>
	<sink name="verticalIntegration_result">
		<ins>
			<in name="verticalIntegrationResult_in" type="org.gumtree.data.gdm.core.Group"/>
		</ins>
	</sink>
	<vars>
		<var name="frame_host" type="java.lang.String" default_value="das1-wombat.nbi.ansto.gov.au" option="das1-wombat.nbi.ansto.gov.au,localhost,default" label="histogram server"/>
		<var name="frame_port" type="java.lang.Integer" default_value="8080" option="8080,8081" label="server port"/>
		<var name="frame_interval" type="java.lang.Double" default_value="30.0" label="Refresh Interval"/>
		<var name="frame_histogramViewerStop" type="java.lang.Boolean" default_value="false" label="stop refreshing"/>
		<var name="frame_dataName" type="java.lang.String" default_value="data" label="name of data"/>
		<var name="frame_verticalIntegrationRegion" type="org.gumtree.data.gdm.core.Group" default_value="null" usage="region" label="region of interests or mask"/>
	    <var name="frame_rescale" type="java.lang.Boolean" default_value="false" usage="parameter" label="Make maximum=10000"/>
	</vars>
	<connectors>
		<connector producer="frame_host" consumer="histogramViewer_host"/>
		<connector producer="frame_port" consumer="histogramViewer_port"/>
		<connector producer="frame_interval" consumer="histogramViewer_interval"/>
		<connector producer="frame_histogramViewerStop" consumer="histogramViewer_stop"/>
		<connector producer="frame_dataName" consumer="source_dataName"/>
		<connector producer="frame_verticalIntegrationRegion" consumer="verticalIntegration_region"/>
		<connector producer="frame_rescale" consumer="vertInt_scale"/>
		<connector producer="histogramViewer_data" consumer="source_groupData"/>
		<connector producer="histogramViewer_loopOut" consumer="histogramViewer_loopIn"/>
		<connector producer="source_scanData" consumer="sourceSink_in"/>
		<connector producer="source_scanData" consumer="verticalIntegration_input"/>
		<connector producer="verticalIntegration_output" consumer="verticalIntegrationResult_in"/>
	</connectors>
	<agents>
		<agent name="histogram_processor" principal="ProcessorAgent" pname="HistogramViewer" label="Histogram Viewer"/>
		<agent name="source_processor" principal="ProcessorAgent" pname="Source" label="Data Source"/>
		<agent name="integration_processor" principal="ProcessorAgent" pname="VerticalIntegration" label="Integration"/>
	</agents>
</framework>

=== Gumtree/gumtree/bragg/wombat/au.gov.ansto.bragg.wombat.dra/xml/efficiencyMapMaker.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : onlineReduction.xml
    Created on : 8 Aug 2007, 16:26
    Author     : nxi
    Description:
        Recipe file of the online reduction processor chain in Wombat algorithm set.
-->
<framework xmlns="http://www.ansto.gov.au/bragg/dra/recipeSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.ansto.gov.au/bragg/dra/recipeSchema http://gumtree.ansto.gov.au:9080/nbicms/dat-projects/data-reduction-capability-projects/cicada-the-dav-application-interface-project/xml-schema/recipe.xsd"
id="031402" 
name="Efficiency Map Producer" 
domain="au.gov.ansto.bragg.wombat.dra" 
version="1.0" 
help_url="./help.txt" 
short_description="Efficiency Map Producer"
icon="xml/icons/WombatDRA.gif">

	<processor name="EfficiencyMapProducer" class="au.gov.ansto.bragg.wombat.dra.core.EfficiencyMapFactory" version="1.0.0">
		<outs>
			<out name="efficiencyMapGroup" type="org.gumtree.data.interfaces.IGroup"/>
		</outs>
		<vars>
		    <var name="efficiencyMapURI" type="java.net.URI"/>
			<var name="backgroundForEfficiencyMapURI" type="java.net.URI"/>
		</vars>
	</processor>
	<processor name="HdfExporter" class="au.gov.ansto.bragg.nbi.dra.export.HdfExporter" version="1.0.0">
		<ins>
			<in name="inputGroup" type="org.gumtree.data.interfaces.IGroup"/>
		</ins>
		<outs>
			<out name="outputGroup" type="org.gumtree.data.interfaces.IGroup"/>
		</outs>
		<vars>
			<var name="saveUri" type="java.net.URI"/>
		</vars>
	</processor>
	<sink name="efficiencyCorrection_result">
		<ins>
			<in name="efficiencyCorrectionResult_in" type="org.gumtree.data.interfaces.IGroup"/>
		</ins>
	</sink>
	<vars>
		<var name="frame_efficiencyMapURI" type="java.net.URI" default_value="null" usage="parameter" label="long run"/>
		<var name="frame_backgroundForEfficiencyMapURI" type="java.net.URI" default_value="null" usage="parameter" label="bcg run"/>
		<var name="frame_saveURI" type="java.net.URI" default_value="null" usage="parameter" label="save to"/>
	</vars>
	<connectors>
		<connector producer="frame_efficiencyMapURI" consumer="efficiencyMapURI"/>
		<connector producer="frame_backgroundForEfficiencyMapURI" consumer="backgroundForEfficiencyMapURI"/>
		<connector producer="frame_saveURI" consumer="saveUri"/>
		<connector producer="efficiencyMapGroup" consumer="efficiencyCorrectionResult_in"/>
		<connector producer="efficiencyMapGroup" consumer="inputGroup"/>
	</connectors>
	<agents>
		<agent name="efficiencyCorrection_processor" principal="ProcessorAgent" pname="EfficiencyMapProducer" label="Efficiency Map Producter"/>
		<agent name="hdfExporter_processor" principal="ProcessorAgent" pname="HdfExporter" label="Efficiency Map Exporter"/>
	</agents>
</framework>
